In [1]:
import numpy as np
import openai

from embed import embed_one, embed_many

In [2]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [3]:
embedding = embed_one("Your text string goes here")

In [4]:
embedding

array([-6.9292835e-03, -5.3364220e-03,  1.1875892e-02, ...,
       -1.7017407e-02, -4.5471323e-05, -2.4047505e-02], dtype=float32)

In [5]:
cat = embed_one("cat")
gato = embed_one("gato")

In [6]:
np.dot(cat, gato)

0.844508

In [7]:
np.dot(cat, embedding)

0.76422906

In [8]:
catruneng = embed_one("The cat runs.")
catrunesp = embed_one("El gato corre.")

In [9]:
np.dot(catruneng, catrunesp)

0.9224194

In [10]:
np.dot(catruneng, embedding)

0.76497674

In [11]:
catruneng.shape

(1536,)

In [12]:
openai.Embedding.create(
    input=["The dog walks.", "El perro camina."],
    model='text-embedding-ada-002',
)

<OpenAIObject list at 0x7efed1c2a0f0> JSON: {
  "data": [
    {
      "embedding": [
        0.009559743106365204,
        -0.006360491272062063,
        -0.0059328689239919186,
        -0.0035730251111090183,
        -0.0024817953817546368,
        0.03121962398290634,
        -0.01407670509070158,
        -0.008767848834395409,
        0.0017168258782476187,
        -0.024631066247820854,
        -0.003959469497203827,
        0.015407087281346321,
        0.01801716908812523,
        -0.011574320495128632,
        0.00899591390043497,
        -0.004798876587301493,
        0.021552182734012604,
        0.00649352977052331,
        0.020437195897102356,
        0.007367780432105064,
        -0.024352319538593292,
        0.020944008603692055,
        0.004969925619661808,
        -0.01899278163909912,
        0.009680110961198807,
        0.0027842987328767776,
        0.017763763666152954,
        -0.007114374544471502,
        0.02176757901906967,
        -0.020475206896662712,
   

In [13]:
catrun = embed_many(["The cat runs.","El gato corre."])
catrun.shape

(2, 1536)

In [14]:
catrun

array([[-0.00909976, -0.00411656, -0.01110068, ..., -0.0247758 ,
         0.0055599 , -0.02420229],
       [-0.01421472, -0.00292079,  0.00039002, ..., -0.00808201,
         0.00493655, -0.00690484]], dtype=float32)

In [15]:
np.dot(catrun[0], catrun[1])

0.9223573

In [17]:
np.dot(catruneng, catrunesp)

0.9224194